### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by bogenschlag** [leifos-gmbh/PermissionManager#2]
I just tried to install the plugin on our production system and got this error when clicking on "Aktualisieren":

```
No plugin record found for 'Services', 'UIComponent', 'uihk', 'PermissionManager'.
```

I had checked out the branch release_5_1 just like on the test system.

**Comment by smeyer-ilias** [comment]
Gib mal bitte in dem plugin Verzeichnis ein
bash> pwd 

ein und schick mir die Ausgabe.

**Comment by bogenschlag** [comment]
```
/srv/www/vhosts/ilias3.uni-stuttgart.de/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/PermissionManager
```

**Comment by bogenschlag** [comment]
Sieht auf dem Test-System aber genauso aus:

```
/srv/www/vhosts/ilias3.uni-stuttgart.de/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/PermissionManager
```

**Comment by smeyer-ilias** [comment]
Ist das Produktivsystem aktuell bzw. wann wurde es das letzte mal aktualisiert?

**Comment by bogenschlag** [comment]
Ja, eigentlich sind bei auf dem gleichen Stand: https://github.com/TIK-NFL/ILIAS/commit/4e3167fc4aeb2f9aa9e3b0fcf25385c7dbf50b07
